services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    networks:
      - elastic_network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.3
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elastic_network

  logstash:
    image: docker.elastic.co/logstash/logstash:7.9.3
    container_name: logstash
    ports:
      - "9600:9600"
    depends_on:
      - elasticsearch
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    networks:
      - elastic_network
  # server:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.server
  #   container_name: server
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - elasticsearch
  #   environment:
  #     - ELASTICSEARCH_URL=http://elasticsearch:9200
  #   networks:
  #     - elastic_network

volumes:
  elastic_data:
networks:
  elastic_network: