name: build-test-scan-web

on:
  workflow_call:

jobs:
  unit-tests:
    uses: ./.github/workflows/unit-test-web.yml
    permissions:
      contents: read
      pull-requests: write

  build-and-push-docker:
    needs: unit-tests
    uses: ./.github/workflows/build-web.yml
    permissions:
      contents: read
      packages: write
          
  cypress-tests:
    needs: build-and-push-docker
    uses: ./.github/workflows/component-test-web.yml

  scan-image:
    needs: build-and-push-docker
    uses: ./.github/workflows/trivvy-scan-web.yml