name: build-web

on:
  workflow_call:

jobs:

  # Build web application, publish dist folder as artifact
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Archive production artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist