name: build-test-scan-web

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    permissions:
      # Required to checkout the code
      contents: read
      # Required to put a comment into the pull-request
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Install dependencies
        run: npm ci
      - name: 'Test'
        run: npx vitest --coverage.enabled true
      - name: 'Report Coverage'
        uses:  davelosert/vitest-coverage-report-action@v2

  build-and-push-docker:
    needs: unit-tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate Image Name
        run: |
          echo "IMAGE_NAME=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.IMAGE_NAME }}/myapp:${{ github.sha }}
          
  cypress-tests:
    needs: build-and-push-docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate Image Name
        run: |
          echo "IMAGE_NAME=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      
      - name: Pull and run Docker image
        run: |
          docker pull ghcr.io/${{ env.IMAGE_NAME }}/myapp:${{ github.sha }}
          docker run -d -p 8080:80 --name myapp ghcr.io/${{ env.IMAGE_NAME }}/myapp:${{ github.sha }}
      
      - name: Wait for Docker container to be ready
        run: |
          until curl -s http://localhost:8080 > /dev/null; do
            echo "Waiting for Docker container to be ready..."
            sleep 5
          done
      
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          command: npm run cypress:run
        env:
          CYPRESS_baseUrl: http://localhost:8080

  scan-image:
    needs: build-and-push-docker
    runs-on: ubuntu-latest

    steps:
      - name: Generate Image Name
        run: |
          echo "IMAGE_NAME=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      - name: Scan Docker image for vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
          scan-type: vuln
          severity: CRITICAL,HIGH
          exit-code: '1'

      - name: Scan Docker image for secrets (optional)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
          scan-type: secret