name: Component Test Web Application

on:
  workflow_call:

jobs:
          
  test:
    runs-on: ubuntu-latest

    steps:
      # Get dist artifact, extract and serve it
      - name: Get dist artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
      - name: Extract dist artifact
        run: tar -xvf dist.tar.gz
      - name: Serve dist artifact
        run: npx serve dist -s -l 8080 &
      # Wait for the server to be ready
      - name: Wait for server to be ready
        run: |
          until curl -s http://localhost:8080 > /dev/null; do
            echo "Waiting for server to be ready..."
            sleep 5
          done
      # Run Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          command: npm run cypress:run
        env:
          CYPRESS_baseUrl: http://localhost:8080