name: Component Test Web Application

on:
  workflow_call:
    inputs:
      node_version:
        description: 'Node.js version'
        type: string
        default: '22'

jobs:
          
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node_version }}
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Serve dist artifact
        run: npx serve dist -s -l 8080 &
      # Wait for the server to be ready
      - name: Wait for server to be ready
        run: |
          until curl -s http://localhost:8080 > /dev/null; do
            echo "Waiting for server to be ready..."
            sleep 5
          done
      # Run Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          command: npm run cypress:run
        env:
          CYPRESS_baseUrl: http://localhost:8080