name: Component Test Web Docker Image

on:
  workflow_call:
    inputs:
      repository-for-image:
        type: string
        description: 'The ECR repository to push the image to'
        required: true
      region:
        type: string
        description: 'The AWS region to deploy to'
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ inputs.region }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      
      - name: Pull and run Docker image
        run: |
          docker pull ${{ steps.login-ecr.outputs.registry }}/${{ inputs.repository-for-image }}:${{ github.sha }}
          docker run -d -p 8080:80 --name myapp ${{ steps.login-ecr.outputs.registry }}/${{ inputs.repository-for-image }}:${{ github.sha }}
      
      - name: Wait for Docker container to be ready
        run: |
          until curl -s http://localhost:8080 > /dev/null; do
            echo "Waiting for Docker container to be ready..."
            sleep 5
          done
      
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          command: npm run cypress:run
        env:
          CYPRESS_baseUrl: http://localhost:8080
