name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Install dependencies
        run: npm ci
      - name: Run Vitest unit tests
        run: npm run test
      - name: Generate coverage report
        run: npm run test:coverage
      - name: 'Report Coverage'
        uses:  davelosert/vitest-coverage-report-action@v2

  build-docker:
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: myapp:latest

  cypress-tests:
    needs: build-docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start Docker container
        run: docker run -d -p 8080:80 --name myapp myapp:latest
      - name: Wait for Docker container to be ready
        run: |
          until curl -s http://localhost:8080 > /dev/null; do
            echo "Waiting for Docker container to be ready..."
            sleep 5
          done
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          command: npm run cypress:run
        env:
          CYPRESS_baseUrl: http://localhost:8080