name: PR Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-scan-web:
    uses: ./.github/workflows/build-test-scan-web.yml
    permissions:
      contents: read
      pull-requests: write
      packages: write