name: PR Pipeline

on:
  push:
    branches: [ main ]

jobs:
  unit-tests:
    uses: ./.github/workflows/unit-test-web.yml
    permissions:
      contents: read
      pull-requests: write

  component-tests:
    uses: ./.github/workflows/component-test-web.yml
    permissions:
      packages: read
      id-token: write
