name: build-web-docker

on:
  workflow_call:

jobs:

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::216989131346:role/GitHubActionsRole
          aws-region: eu-west-2
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      
      - name: Deploy to App Runner
        uses: awslabs/amazon-app-runner-deploy@main
        with:
          service: github-actions-testing-service
          image: ${{ steps.login-ecr.outputs.registry }}/github-actions-testing/containers:${{ github.sha }}
          region: eu-west-2
          cpu: 1
          memory: 2
          port: 80
          wait-for-service-stability: true