name: build-web-docker

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: 'The environment to deploy to'
        required: true
      app-runner-service-name:
        type: string
        description: 'The name of the App Runner service'
        required: true

jobs:

  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::216989131346:role/GitHubActionsRole
          aws-region: eu-west-2
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      
      - name: Deploy to App Runner
        uses: awslabs/amazon-app-runner-deploy@main
        with:
          access-role-arn: arn:aws:iam::216989131346:role/service-role/AppRunnerECRAccessRole
          service: ${{ inputs.app-runner-service-name }}
          image: ${{ steps.login-ecr.outputs.registry }}/github-actions-testing/containers:${{ github.sha }}
          region: eu-west-2
          cpu: 1
          memory: 2
          port: 80
          wait-for-service-stability-seconds: 600