name: 🚀 Publish Build To App Runner

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: 'The environment to deploy to'
        required: true
      app-runner-service-name:
        type: string
        description: 'The name of the App Runner service'
        required: true
      repository-for-image:
        type: string
        description: 'The ECR repository to pull the image from'
        required: true
      region:
        type: string
        description: 'The AWS region to deploy to'
        required: true
      cpu:
        type: number
        description: 'The number of CPU cores to allocate to the service'
        required: false
      memory:
        type: number
        description: 'The memory to allocate to the service in GB'
        required: false
      port:
        type: number
        description: 'The port the service listens on'
        required: false

jobs:

  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ inputs.region }}
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      
      - name: Deploy to App Runner
        uses: awslabs/amazon-app-runner-deploy@main
        with:
          access-role-arn: ${{ secrets.AWS_APP_RUNNER_ROLE_TO_ASSUME }}
          service: ${{ inputs.app-runner-service-name }}
          image: ${{ steps.login-ecr.outputs.registry }}/${{ inputs.repository-for-image }}:${{ github.sha }}
          region: ${{ inputs.region }}
          cpu: ${{ inputs.cpu || 1 }}
          memory: ${{ inputs.memory || 2 }}
          port: ${{ inputs.port || 80 }}
          wait-for-service-stability-seconds: 600