name: trivvy-scan-web

on:
  workflow_call:
  
jobs:
  scan-image:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Image Name
        run: |
          echo "IMAGE_NAME=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      - name: Scan Docker image for vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
          scan-type: vuln
          severity: CRITICAL,HIGH
          exit-code: '1'

      - name: Scan Docker image for secrets
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
          scan-type: secret