name: Update Coverage Badge

on:
  push:
    branches:
      - main

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '22'
      - run: npm ci
      - run: npm run test:coverage
      - name: Generate coverage percentage
        id: coverage
        run: |
          COVERAGE=$(node -e "console.log(JSON.parse(require('fs').readFileSync('coverage/coverage-summary.json', 'utf8')).total.lines.pct)")
          echo "percentage=$COVERAGE" >> $GITHUB_OUTPUT
      - name: Update Gist
        run: |
          COVERAGE=$(node -e "console.log(JSON.parse(require('fs').readFileSync('coverage/coverage-summary.json', 'utf8')).total.lines.pct)")
          
          # Determine color based on coverage percentage
          if (( $(echo "$COVERAGE < 50" | bc -l) )); then
            COLOR="red"
          elif (( $(echo "$COVERAGE < 60" | bc -l) )); then
            COLOR="orange"
          elif (( $(echo "$COVERAGE < 70" | bc -l) )); then
            COLOR="yellowgreen"
          elif (( $(echo "$COVERAGE < 80" | bc -l) )); then
            COLOR="yellow"
          elif (( $(echo "$COVERAGE < 90" | bc -l) )); then
            COLOR="green"
          else
            COLOR="brightgreen"
          fi
          
          GIST_CONTENT=$(jq -n \
            --arg label "coverage" \
            --arg message "$COVERAGE%" \
            --arg color "$COLOR" \
            '{schemaVersion: 1, $label, $message, $color}' | jq -r tostring)
          
          curl -L \
            -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GIST_SECRET }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/gists/${{ vars.GIST_ID }} \
            -d "{\"files\":{\"coverage.json\":{\"content\":$(jq -n --arg content "$GIST_CONTENT" '$content')}}}"