name: Update Coverage Badge

on:
  push:
    branches:
      - main

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '22'
      - run: npm ci
      - run: npm run test:coverage
      - name: Generate coverage percentage
        id: coverage
        run: |
          COVERAGE=$(node -e "console.log(JSON.parse(require('fs').readFileSync('coverage/coverage-summary.json', 'utf8')).total.lines.pct)")
          echo "percentage=$COVERAGE" >> $GITHUB_OUTPUT
      - name: Update Gist
        run: |
          COVERAGE=$(node -e "console.log(JSON.parse(require('fs').readFileSync('coverage/coverage-summary.json', 'utf8')).total.lines.pct)")
          GIST_CONTENT=$(jq -n \
            --arg label "coverage" \
            --arg message "$COVERAGE%" \
            --arg color "brightgreen" \
            '{schemaVersion: 1, $label, $message, $color}')
          curl -L \
            -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GIST_SECRET }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/gists/${{ vars.GIST_ID }} \
            -d "{\"files\":{\"coverage.json\":{\"content\":$GIST_CONTENT}}}"